"""fixed title in task

Revision ID: 222e1db96051
Revises: be20d2d4856f
Create Date: 2025-11-19 13:12:52.058194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222e1db96051'
down_revision = 'be20d2d4856f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###