"""fixed title in task

Revision ID: 3786cae2f3d5
Revises: 222e1db96051
Create Date: 2025-11-19 13:37:53.314324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3786cae2f3d5'
down_revision = '222e1db96051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###