"""fixed title in task

Revision ID: be20d2d4856f
Revises: df2e8336b5c4
Create Date: 2025-11-19 13:11:42.647952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be20d2d4856f'
down_revision = 'df2e8336b5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=True)
    # ### end Alembic commands ###