"""Changed table Tasks

Revision ID: df2e8336b5c4
Revises: b5266ff5b85a
Create Date: 2025-11-17 16:58:25.707750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2e8336b5c4'
down_revision = 'b5266ff5b85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###